name: Test Runner Resources
on:
  push:
    paths:
      - 'app_lianxi/mdio/**'
      - '.github/workflows/mdio.yml'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        working-directory: app_lianxi/mdio
        run: |
          make clean && make

